export const videos = [
    {
        id: '1',
        thumbnailURL: 'http://img.youtube.com/vi/8aGhZQkoFbQ/0.jpg',
        videoURL: 'https://youtu.be/8aGhZQkoFbQ',
        title: 'Title1',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged',
        author: 'author1',
        views: '230',
        likes: '100',
        dislikes: '12',
        uploadedDate: '23/02/21',
        comments: [],
        duration: '2:34',
        type: 'youtube'
    },
    {
        id: '2',
        thumbnailURL: 'http://img.youtube.com/vi/TQQPAU21ZUw/0.jpg',
        videoURL: 'https://youtu.be/TQQPAU21ZUw',
        title: 'Title2',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged',
        author: 'author2',
        views: '2300',
        likes: '1002',
        dislikes: '121',
        uploadedDate: '29/02/21',
        comments: [],
        duration: '21:34',
        type: 'youtube'
    },
    {
        id: '3',
        thumbnailURL: 'http://img.youtube.com/vi/Ep78KjstQuw/0.jpg',
        videoURL: 'https://youtu.be/Ep78KjstQuw',
        title: 'Title3',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged',
        author: 'author3',
        views: '230',
        likes: '10000',
        dislikes: '120',
        uploadedDate: '23/02/21',
        comments: [],
        duration: '6:34',
        type: 'youtube'
    },
    {
        id: '4',
        thumbnailURL: 'https://images.unsplash.com/photo-1605135693932-f1d6fb1be3cc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjB8fGZvb3RiYWxsfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
        videoURL: '',
        title: 'Title4',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged',
        author: 'author4',
        views: '8700',
        likes: '1000',
        dislikes: '500',
        uploadedDate: '23/02/2008',
        comments: [],
        duration: '34'
    }
]