export const videos = [
    {
        id: '1',
        thumbnailURL: 'http://img.youtube.com/vi/8aGhZQkoFbQ/0.jpg',
        videoURL: 'https://youtu.be/8aGhZQkoFbQ',
        title: 'Title1',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged',
        author: 'author1',
        views: '230',
        likes: '100',
        dislikes: '12',
        uploadedDate: '23/02/21',
        comments: [],
        duration: '2:34',
        type: 'youtube'
    },
    {
        id: '2',
        thumbnailURL: 'http://img.youtube.com/vi/TQQPAU21ZUw/0.jpg',
        videoURL: 'https://youtu.be/TQQPAU21ZUw',
        title: 'Title2',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged',
        author: 'author2',
        views: '2300',
        likes: '1002',
        dislikes: '121',
        uploadedDate: '29/02/21',
        comments: [],
        duration: '21:34',
        type: 'youtube'
    },
    {
        id: '3',
        thumbnailURL: 'http://img.youtube.com/vi/Ep78KjstQuw/0.jpg',
        videoURL: 'https://youtu.be/Ep78KjstQuw',
        title: 'Title3',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged',
        author: 'author3',
        views: '230',
        likes: '10000',
        dislikes: '120',
        uploadedDate: '23/02/21',
        comments: [],
        duration: '6:34',
        type: 'youtube'
    },
    {
        id: '4',
        thumbnailURL: 'http://img.youtube.com/vi/JbGjZk_EQpg/0.jpg',
        videoURL: 'https://youtu.be/JbGjZk_EQpg',
        title: 'Masters or not?',
        description: 'Episode 4 of the Career Conversation series. All links mentioned can be found at https://tanaypratap.com',
        author: 'Tanay Pratap',
        views: '230',
        likes: '10000',
        dislikes: '120',
        uploadedDate: '23/02/21',
        comments: [],
        duration: '48:40',
        type: 'youtube'
    },
    {
        id: '5',
        thumbnailURL: 'http://img.youtube.com/vi/1ZxINYZpLWc/0.jpg',
        videoURL: 'https://youtu.be/1ZxINYZpLWc',
        title: 'GRIEZMANN, DE JONG, DEMBÉLÉ... 💥VS💥 BRAITHWAITE, PIQUÉ, TRINCAO...',
        description: "This Sunday morning, the first-team squad had their penultimate training session before facing Sergio González's Real Valladolid (Monday, 9.00pm CEST). The session took place on the Tito Vilanova pitch at the Ciutat Esportiva, with Gerard Piqué joining the group as preparations for the match continued.",
        author: 'FC Barcelona',
        views: '230',
        likes: '10000',
        dislikes: '120',
        uploadedDate: '23/02/21',
        comments: [],
        duration: '3:38',
        type: 'youtube'
    },
    {
        id: '6',
        thumbnailURL: 'http://img.youtube.com/vi/QokA6knnkA0/0.jpg',
        videoURL: 'https://youtu.be/QokA6knnkA0',
        title: 'Vegeta kills Captain Ginyu',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged',
        author: 'ImmaVegeta',
        views: '230',
        likes: '10000',
        dislikes: '120',
        uploadedDate: '31/July/2017',
        comments: [],
        duration: '1:20',
        type: 'youtube'
    },
    {
        id: '7',
        thumbnailURL: 'http://img.youtube.com/vi/_L-UszPmy2A/0.jpg',
        videoURL: 'https://youtu.be/_L-UszPmy2A',
        title: 'First CLI App: Intro to programming',
        description: "Welcome to neogcamp's first class. This is the most basic class you'll find on programming. We will use JavaScript to code. Using nodeJS we will write a CLI (Command Line Interface) program. We'll then use https://repl.it​ to host it. For intermediate to advanced developers, this class would be too basic. Therefore, you can skip this and directly make the app for the camp's submission for levelOne.",
        author: 'Tanay Pratap',
        views: '230',
        likes: '10000',
        dislikes: '120',
        uploadedDate: '14/Nov/2020',
        comments: [],
        duration: '2:45:24',
        type: 'youtube'
    },
    {
        id: '8',
        thumbnailURL: 'http://img.youtube.com/vi/Ezk2AwqgS9Q/0.jpg',
        videoURL: 'https://youtu.be/Ezk2AwqgS9Q',
        title: 'launching neog.camp: roadmap to full stack dev',
        description: "neog.camp is one of its kind bootcamp where we are taking absolute beginners and getting them to a full stack web dev level in 6 months. In this session, I will be walking you through the structure of the camp. And will take questions from the live chat. If you already know about the camp, you can skip this session and save your time.",
        author: 'Tanay Pratap',
        views: '230',
        likes: "210000",
        dislikes: '120',
        uploadedDate: '12/11/20',
        comments: [],
        duration: '48:45',
        type: 'youtube'
    },
    {
        id: '9',
        thumbnailURL: 'http://img.youtube.com/vi/MMEIVh49pS8/0.jpg',
        videoURL: 'https://youtu.be/MMEIVh49pS8',
        title: 'Getting started with Git, VSCode and Hosting',
        description: "Welcome to neogcamp's second class. For a newbie to self host his/her first website and program more apps we need some tooling to be in place. Tools help you make your life easier. All these tools are free for you and will give you a better place to code, a place to store your code in the cloud so that you don't lose it, and then a place to host your app so that others can find it. This session will set you up for the next class where we'll develop our very own portfolio website and blog. The blog part will be an assignment but I'll help you with that. For intermediate to advanced developers, if you already know how to use Git, Github, VSCode, Netlify, etc to do web development you can skip this class.",
        author: 'Tanay Pratap',
        views: '230',
        likes: '100000',
        dislikes: '120',
        uploadedDate: '21/11/20',
        comments: [],
        duration: '2:15:9',
        type: 'youtube'
    },
    {
        id: '10',
        thumbnailURL: 'http://img.youtube.com/vi/No8qdcVYiQw/0.jpg',
        videoURL: 'https://youtu.be/No8qdcVYiQw',
        title: 'Getting started with HTML5',
        description: "Welcome to neogcamp's levelZero journey. You don't know anything about web development? Good, you have come to the right place. Not only you'll learn the language of the web: HTML, you'll learn how to make your site pretty with CSS. When we have learned everything we will put together a decent profile to host your Internet adventures. ",
        author: 'Tanay Pratap',
        views: '230',
        likes: '106500',
        dislikes: '12',
        uploadedDate: '22/11/20',
        comments: [],
        duration: '1:45:20',
        type: 'youtube'
    },
    {
        id: '11',
        thumbnailURL: 'http://img.youtube.com/vi/u6_a0d94A1Q/0.jpg',
        videoURL: 'https://youtu.be/u6_a0d94A1Q',
        title: 'Getting started with CSS3',
        description: "entative Duration: 2 hours. Back after break from first session of today. This time we will do CSS. Welcome to neogcamp's levelZero journey. You don't know anything about web development? Good, you have come to the right place. Not only you'll learn the language of the web: HTML, you'll learn how to make your site pretty with CSS. When we have learned everything we will put together a decent profile to host your Internet adventures.",
        author: 'Tanay Pratap',
        views: '230',
        likes: '100000',
        dislikes: '3',
        uploadedDate: '22/11/20',
        comments: [],
        duration: '2:17:32',
        type: 'youtube'
    },
]